### PR TITLE
Yairs additions

### PR DESCRIPTION
**Pull request by yairdaon**
I made some changes that I believe will make the package run smoother. I tried to use it but generating surrogates took too much time. The main changes I added are parallelisation (via joblib) and vectorization (with numpy and numba)

### CODE REVIEW

**Comment by VSainteuf** [comment]
Hi @yairdaon , thanks for your PR!
I went through your modifications and most of it looks good to me.
I only have 4 points I want to discuss:

1. in `utils.py/projection`. I don't think that the formula in `np.einsum` is correct as it does not yield the same result as the original formula. The following minimal example returns `False`.
```python3
import numpy as np
from scipy.linalg import eig

X = np.random.rand(100,15)
C = X.transpose()@X
values, E = eig(C)

np.diagonal(E.transpose()*C*E) == np.einsum('ki, kj, ji -> i', E, C, E) 
```

2. Line 254 of `mcssa.py`, can you explain the rationale of adding the division by (1-gamma**2) to the formula ?

3. In `arfitting.py/projmat` I would rather have the function return the identity matrix when all components are taken. To ensure that the function outputs a consistent type. 

4. Regarding the way filtered components are labelled when passed as argument for reconstruction, or filtering in mc-ssa. Did you change the convention from 1 -> M to  0 -> M-1?

**Comment by yairdaon** [comment]
Hi @VSainteuf , thanks for considering my PR!

1. I think you mixed pointwise and matrix multiplication in your example. If you replace `*` with `@` in the last line, and require "almost equality" (e.g. to 10 decimal points) the code returns `True`.

    import numpy as np
    from scipy.linalg import eig

    X = np.random.rand(100,15)
    C = X.transpose()@X
    values, E = eig(C)

    np.max(np.abs(np.diagonal(E.transpose()@C@E) - np.einsum('ki, kj, ji -> i', E, C, E))) < 1e-10 

2. Take an AR(1) process $X_{t+1} = \gamma X_t + \alpha \epsilon_t$, where $|\gamma| <1$ and $\epsilon_t \sim \mathcal{N}(0,1)$ are IID. I assume this process is in its stationary distribution (i.e. it is "running for a long time"). Clearly $\mathbb{E}[X_t] = 0$ for all $t$, so the mean is zero. What is the variance $Var(X_t)$? If the process has reached its stationary distribution, then  $Var(X_{t+1}) = Var(X_t)$. Thus $Var(X_{t+1}) = \gamma^2 Var(X_t) + \alpha^2$. Solving for said variance, we get $Var(X_t)= \frac{\alpha^2}{1-\gamma^2}$. Thus, in order to correctly sample the first term we take $X_0 = \epsilon_0 \frac{\alpha}{\sqrt{1-\gamma^2}}$. So I actually made a mistake, we need to divide the first term by $\sqrt{1-\gamma^2}$, and not what I wrote. Sorry for that.
3. Makes sense.
4. You are correct, I did. I failed to mention that. I think this convention is more pythonic.

**Comment by VSainteuf** [comment]
Hi again,

1. yes good point, my bad.
2. ok understood!
3. Cool
4. Ok, yes at least it will remove some ambiguity in the different variables. I'll just need to make this more explicit in the docstring. 

Can you push the modifications for points 2 and 3? and I'll merge the PR.
Cheers

**Comment by yairdaon** [comment]
@VSainteuf  I'm not sure I understand. Only 2 and 3? And what about all the other changes?

**Comment by VSainteuf** [comment]
Hey, sorry if it was not clear! 
I meant that you can push additional commits to your current PR. So point 1 and 4 don't need additional modifications. Only the square root has to be added for point 2 and the output of `projmat` changed for point 3. 
Is it more clear ?

**Comment by yairdaon** [comment]
@VSainteuf OK I pushed a new commit.

**Comment by VSainteuf** [comment]
Hi @yairdaon, thank you!
It looks like your additional commit did not fix the square root problem (point 2 of our discussion), it's still $(1 - \gamma^2)$ . 
Maybe you forgot to stage the file before committing ?

**Comment by yairdaon** [comment]
@VSainteuf very perceptive of you, I indeed forgot to stage it. Thanks!

**Comment by VSainteuf** [comment]
haha no worries :)

**Pull request merged**
